#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: patches/apply_patches.sh [--patch-dir <dir>] [--check] [--allow-dirty]

Apply numbered patches generated by generate_patches.sh in lexical order.

Defaults:
  --patch-dir <script directory>

Recommended workflow:
  git switch main
  patches/apply_patches.sh --check
  patches/apply_patches.sh

Options:
  --check         Only verify that all patches can apply; do not modify files.
  --allow-dirty   Allow applying into a dirty working tree. By default this is refused.
USAGE
}

patch_dir=""
check_only=0
allow_dirty=0

while (($#)); do
    case "$1" in
        --patch-dir)
            [[ $# -ge 2 ]] || { echo "missing value for --patch-dir" >&2; exit 2; }
            patch_dir="$2"
            shift 2
            ;;
        --check)
            check_only=1
            shift
            ;;
        --allow-dirty)
            allow_dirty=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

repo_root=$(git rev-parse --show-toplevel)
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

if [[ -z "$patch_dir" ]]; then
    patch_dir="$script_dir"
fi
patch_dir=$(cd -- "$patch_dir" && pwd)

cd "$repo_root"

if (( ! allow_dirty )); then
    if [[ -n "$(git status --porcelain)" ]]; then
        echo "working tree is not clean; commit/stash changes or pass --allow-dirty" >&2
        exit 1
    fi
fi

mapfile -t patches < <(find "$patch_dir" -maxdepth 1 -type f -name '[0-9][0-9][0-9]-*.patch' | LC_ALL=C sort)

if ((${#patches[@]} == 0)); then
    echo "no numbered patches found in: $patch_dir" >&2
    exit 1
fi

for patch in "${patches[@]}"; do
    echo "CHECK $(basename "$patch")"
    git apply --check --whitespace=nowarn "$patch"
done

if ((check_only)); then
    echo "check_only=1"
    echo "patch_count=${#patches[@]}"
    echo "all patches can be applied"
    exit 0
fi

for patch in "${patches[@]}"; do
    echo "APPLY $(basename "$patch")"
    git apply --whitespace=nowarn "$patch"
done

echo "patch_count=${#patches[@]}"
echo "all patches applied"
