#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: patches/apply_patches.sh [--patch-dir <dir>] [--check] [--allow-dirty]
       patches/apply_patches.sh --verify-tree [--base <ref>] [--patch-dir <dir>] [--allow-dirty]

Apply numbered patches generated by generate_patches.sh in lexical order.

Defaults:
  --patch-dir <script directory>
  --base main

Recommended workflow:
  git switch main
  patches/apply_patches.sh --check
  patches/apply_patches.sh

Verification workflow from a feature branch:
  patches/apply_patches.sh --verify-tree --base main

Options:
  --check         Only verify that all patches can apply; do not modify files.
  --verify-tree   Apply patches to a temporary <base> worktree and compare the
                  resulting non-patches tree diff with the current branch.
  --base <ref>    Base ref used by --verify-tree.
  --allow-dirty   Allow applying into a dirty working tree. For --verify-tree,
                  this only allows dirty files outside patches/.
USAGE
}

patch_dir=""
check_only=0
allow_dirty=0
verify_tree=0
base_ref="main"

while (($#)); do
    case "$1" in
        --patch-dir)
            [[ $# -ge 2 ]] || { echo "missing value for --patch-dir" >&2; exit 2; }
            patch_dir="$2"
            shift 2
            ;;
        --check)
            check_only=1
            shift
            ;;
        --verify-tree)
            verify_tree=1
            shift
            ;;
        --base)
            [[ $# -ge 2 ]] || { echo "missing value for --base" >&2; exit 2; }
            base_ref="$2"
            shift 2
            ;;
        --allow-dirty)
            allow_dirty=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

repo_root=$(git rev-parse --show-toplevel)
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

if [[ -z "$patch_dir" ]]; then
    patch_dir="$script_dir"
fi
patch_dir=$(cd -- "$patch_dir" && pwd)

cd "$repo_root"

git rev-parse --verify --quiet "$base_ref^{commit}" >/dev/null || {
    echo "base ref not found: $base_ref" >&2
    exit 2
}

mapfile -t patches < <(find "$patch_dir" -maxdepth 1 -type f -name '[0-9][0-9][0-9]-*.patch' | LC_ALL=C sort)

if ((${#patches[@]} == 0)); then
    echo "no numbered patches found in: $patch_dir" >&2
    exit 1
fi

apply_numbered_patches() {
    for patch in "${patches[@]}"; do
        echo "CHECK $(basename "$patch")"
        git apply --check --whitespace=nowarn "$patch"
    done

    if ((check_only)); then
        echo "check_only=1"
        echo "patch_count=${#patches[@]}"
        echo "all patches can be applied"
        return
    fi

    for patch in "${patches[@]}"; do
        echo "APPLY $(basename "$patch")"
        git apply --whitespace=nowarn "$patch"
    done

    echo "patch_count=${#patches[@]}"
    echo "all patches applied"
}

verify_tree_matches_current_branch() {
    if (( ! allow_dirty )); then
        if [[ -n "$(git status --porcelain -- . ':(exclude)patches')" ]]; then
            echo "working tree has non-patches changes; commit/stash them or pass --allow-dirty" >&2
            exit 1
        fi
    fi

    local tmp_parent
    local verify_worktree
    local applied_diff
    local current_diff
    tmp_parent=$(mktemp -d "${TMPDIR:-/tmp}/asterinas-patch-verify.XXXXXX")
    verify_worktree="$tmp_parent/worktree"
    applied_diff="$tmp_parent/applied.diff"
    current_diff="$tmp_parent/current.diff"

    git worktree add --detach "$verify_worktree" "$base_ref" >/dev/null

    if ! (
        cd "$verify_worktree"
        "$script_dir/apply_patches.sh" --patch-dir "$patch_dir" --allow-dirty
        git add -A -- . ':(exclude)patches'
        git diff --cached --binary HEAD -- . ':!patches' > "$applied_diff"
    ); then
        echo "verify worktree kept: $verify_worktree" >&2
        exit 1
    fi

    git diff --binary "$base_ref" -- . ':!patches' > "$current_diff"

    if cmp -s "$applied_diff" "$current_diff"; then
        git worktree remove --force "$verify_worktree" >/dev/null
        rm -rf -- "$tmp_parent"
        echo "verify_tree=1"
        echo "base_ref=$base_ref"
        echo "patch_count=${#patches[@]}"
        echo "patched tree matches current branch outside patches/"
    else
        echo "patched tree differs from current branch outside patches/" >&2
        echo "verify worktree kept: $verify_worktree" >&2
        echo "applied diff: $applied_diff" >&2
        echo "current diff: $current_diff" >&2
        exit 1
    fi
}

if (( verify_tree )); then
    if (( check_only )); then
        echo "--check cannot be combined with --verify-tree" >&2
        exit 2
    fi
    verify_tree_matches_current_branch
    exit 0
fi

if (( ! allow_dirty )); then
    if [[ -n "$(git status --porcelain)" ]]; then
        echo "working tree is not clean; commit/stash changes or pass --allow-dirty" >&2
        exit 1
    fi
fi

apply_numbered_patches
